name: curso
channels:
  - conda-forge
  - defaults
dependencies:
  - wordcloud
  - zlib
  - gensim
  - ipykernel
  - ipython
  - ipython_genutils
  - jsonschema=2.6.0=py37_0
  - jupyter_client=5.2.3=py37_0
  - jupyter_core=4.4.0=py37_0
  - matplotlib
  - nltk=3.3.0=py37_0
  - notebook=5.7.0=py37_0
  - numpy
  - numpy-base
  - openssl
  - pandas
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - parso=0.3.1=py37_0
  - pickleshare=0.7.5=py37_0
  - pip=10.0.1=py37_0
  - pycparser=2.19=py37_0
  - pygments=2.2.0=py37_0
  - pyopenssl=18.0.0=py37_0
  - pyparsing=2.2.2=py37_0
  - requests=2.19.1=py37_0
  - scikit-learn
  - scipy
  - setuptools=40.4.3=py37_0
  - urllib3=1.23=py37_0

